config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, {
    path: :account,
    controllers: {
      confirmations: "auth/confirmations",
      passwords: "auth/passwords",
      sessions: "auth/sessions",
      two_factor_authentication: "auth/two_factor_authentication",
    },
    path_names: {
      sign_in: "sign-in",
      sign_out: "sign-out",
      two_factor_authentication: "two-factor-authentication",
      two_factor_authentication_resend_code: "resend-code",
    },
    sign_out_via: %i[get],
  }

  devise_scope :user do
    get "account/password/reset-confirmation", to: "auth/passwords#reset_confirmation"
    get "account/two-factor-authentication/resend", to: "auth/two_factor_authentication#show_resend", as: "user_two_factor_authentication_resend"
    put "account", to: "users#update"
  end

  get "/health", to: ->(_) { [204, {}, [nil]] }

  root to: "start#index"

  get "/accessibility-statement", to: "content#accessibility_statement"
  get "/privacy-notice", to: "content#privacy_notice"
  get "/data-sharing-agreement", to: "content#data_sharing_agreement"

  resource :account, only: %i[show edit], controller: "users" do
    get "edit/password", to: "users#edit_password"
  end

  resources :schemes do
    get "primary-client-group", to: "schemes#primary_client_group"
    get "confirm-secondary-client-group", to: "schemes#confirm_secondary_client_group"
    get "secondary-client-group", to: "schemes#secondary_client_group"
    get "support", to: "schemes#support"
    get "details", to: "schemes#details"
    get "check-answers", to: "schemes#check_answers"
    get "edit-name", to: "schemes#edit_name"
    get "support-services-provider", to: "schemes#support_services_provider"

    member do
      resources :locations do
        get "edit-name", to: "locations#edit_name"
      end
    end
  end

  resources :users do
    member do
      get "deactivate", to: "users#deactivate"
      get "reactivate", to: "users#reactivate"
    end
  end

  resources :organisations do
    member do
      get "details", to: "organisations#details"
      get "users", to: "organisations#users"
      get "users/invite", to: "users/account#new"
      get "logs", to: "organisations#logs"
      get "schemes", to: "organisations#schemes"
    end
  end

  resources :case_logs, path: "/logs" do
    collection do
      post "bulk-upload", to: "bulk_upload#bulk_upload"
      get "bulk-upload", to: "bulk_upload#show"
    end

    member do
      post "form", to: "form#submit_form"
      get "review", to: "form#review"
    end

    FormHandler.instance.forms.each do |_key, form|
      form.pages.map do |page|
        get page.id.to_s.dasherize, to: "form##{page.id}"
      end

      form.subsections.map do |subsection|
        get "#{subsection.id.to_s.dasherize}/check-answers", to: "form#check_answers"
      end
    end
  end

  scope via: :all do
    match "/404", to: "errors#not_found"
    match "/429", to: "errors#too_many_requests", status: 429
    match "/422", to: "errors#unprocessable_entity"
    match "/500", to: "errors#internal_server_error"
  end
end

app/models/form/setup/pages/scheme.rb
class Form::Setup::Pages::Scheme < ::Form::Page
  def initialize(_id, hsh, subsection)
    super("scheme", hsh, subsection)
    @header = ""
    @description = ""
    @questions = questions
    @depends_on = [{
      "supported_housing_schemes_enabled?" => true,
      "needstype" => 2,
    }]
  end

  def questions
    [
      Form::Setup::Questions::SchemeId.new(nil, nil, self),
    ]
  end
end

app/controllers/schemes_controller.rb
class SchemesController < ApplicationController
  include Pagy::Backend
  include Modules::SearchFilter

  before_action :authenticate_user!
  before_action :find_resource, except: %i[index]
  before_action :authenticate_scope!

  def index
    flash[:notice] = "#{Scheme.find(params[:scheme_id].to_i).service_name} has been created." if params[:scheme_id]
    redirect_to schemes_organisation_path(current_user.organisation) unless current_user.support?
    all_schemes = Scheme.all.order("service_name ASC")

    @pagy, @schemes = pagy(filtered_collection(all_schemes, search_term))
    @searched = search_term.presence
    @total_count = all_schemes.size
  end

  def show
    @scheme = Scheme.find_by(id: params[:id])
  end

  def new
    @scheme = Scheme.new
  end

  def create
    @scheme = Scheme.new(scheme_params)

    validation_errors scheme_params

    if @scheme.errors.empty? && @scheme.save
      if @scheme.arrangement_type_before_type_cast == "D"
        redirect_to scheme_primary_client_group_path(@scheme)
      else
        redirect_to scheme_support_services_provider_path(@scheme)
      end
    else
      @scheme.errors.add(:owning_organisation_id, message: @scheme.errors[:organisation])
      @scheme.errors.delete(:owning_organisation)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    check_answers = params[:scheme][:check_answers]
    page = params[:scheme][:page]

    validation_errors scheme_params
    if @scheme.errors.empty? && @scheme.update(scheme_params)
      if check_answers
        if confirm_secondary_page? page
          redirect_to scheme_secondary_client_group_path(@scheme, check_answers: "true")
        else
          @scheme.update!(secondary_client_group: nil) if @scheme.has_other_client_group == "No"
          redirect_to scheme_check_answers_path(@scheme)
        end
      else
        redirect_to next_page_path params[:scheme][:page]
      end
    else
      render current_template(page), status: :unprocessable_entity
    end
  end

  def primary_client_group
    if @scheme.confirmed?
      redirect_to @scheme
    else
      render "schemes/primary_client_group"
    end
  end

  def confirm_secondary_client_group
    if @scheme.confirmed?
      redirect_to @scheme
    else
      render "schemes/confirm_secondary"
    end
  end

  def secondary_client_group
    if @scheme.confirmed?
      redirect_to @scheme
    else
      render "schemes/secondary_client_group"
    end
  end

  def support
    if @scheme.confirmed?
      redirect_to @scheme
    else
      render "schemes/support"
    end
  end

  def details
    if @scheme.confirmed?
      redirect_to @scheme
    else
      render "schemes/details"
    end
  end

  def check_answers
    if @scheme.confirmed?
      redirect_to @scheme
    else
      render "schemes/check_answers"
    end
  end

  def edit_name
    render "schemes/edit_name"
  end

  def support_services_provider
    render "schemes/support_services_provider"
  end

private

  def validation_errors(scheme_params)
    scheme_params.each_key do |key|
      if scheme_params[key].to_s.empty?
        @scheme.errors.add(key.to_sym)
      end
    end

    if @scheme.arrangement_type_same? && arrangement_type_value(scheme_params[:arrangement_type]) != "D"
      @scheme.errors.delete(:managing_organisation_id)
    end
  end

  def confirm_secondary_page?(page)
    page == "confirm-secondary" && @scheme.has_other_client_group == "Yes"
  end

  def current_template(page)
    if page.include?("primary")
      "schemes/primary_client_group"
    elsif page.include?("support-services-provider")
      "schemes/support_services_provider"
    elsif page.include?("confirm")
      "schemes/confirm_secondary"
    elsif page.include?("secondary-client")
      "schemes/secondary_client_group"
    elsif page.include?("support")
      "schemes/support"
    elsif page.include?("details")
      "schemes/details"
    elsif page.include?("edit")
      "schemes/edit_name"
    elsif page.include?("check-answers")
      "schemes/check_answers"
    end
  end

  def next_page_path(page)
    case page
    when "support-services-provider"
      scheme_primary_client_group_path(@scheme)
    when "primary-client-group"
      scheme_confirm_secondary_client_group_path(@scheme)
    when "confirm-secondary"
      @scheme.has_other_client_group == "Yes" ? scheme_secondary_client_group_path(@scheme) : scheme_support_path(@scheme)
    when "secondary-client-group"
      scheme_support_path(@scheme)
    when "support"
      new_location_path
    when "details"
      if @scheme.arrangement_type_before_type_cast == "D"
        scheme_primary_client_group_path(@scheme)
      elsif @scheme.arrangement_type.present? && @scheme.arrangement_type_before_type_cast != "D"
        scheme_support_services_provider_path(@scheme)
      else
        scheme_details_path(@scheme)
      end
    when "edit-name"
      scheme_path(@scheme)
    when "check-answers"
      schemes_path(scheme_id: @scheme.id)
    end
  end

  def scheme_params
    required_params = params.require(:scheme).permit(:service_name,
                                                     :sensitive,
                                                     :owning_organisation_id,
                                                     :managing_organisation_id,
                                                     :scheme_type,
                                                     :registered_under_care_act,
                                                     :id,
                                                     :has_other_client_group,
                                                     :primary_client_group,
                                                     :secondary_client_group,
                                                     :support_type,
                                                     :arrangement_type,
                                                     :intended_stay,
                                                     :confirmed)

    if arrangement_type_changed_to_different_org?(required_params)
      required_params[:managing_organisation_id] = nil
    end

    if arrangement_type_set_to_same_org?(required_params)
      required_params[:managing_organisation_id] = required_params[:owning_organisation_id] || @scheme.owning_organisation_id
    end

    required_params[:sensitive] = required_params[:sensitive].to_i if required_params[:sensitive]

    if current_user.data_coordinator?
      required_params[:owning_organisation_id] = current_user.organisation_id
    end
    required_params
  end

  def arrangement_type_set_to_same_org?(required_params)
    arrangement_type_value(required_params[:arrangement_type]) == "D" || (required_params[:arrangement_type].blank? && @scheme.present? && @scheme.arrangement_type_same?)
  end

  def arrangement_type_changed_to_different_org?(required_params)
    @scheme.present? && @scheme.arrangement_type_same? && arrangement_type_value(required_params[:arrangement_type]) != "D" && required_params[:managing_organisation_id].blank?
  end

  def arrangement_type_value(key)
    key.present? ? Scheme::ARRANGEMENT_TYPE[key.to_sym] : nil
  end

  def search_term
    params["search"]
  end

  def find_resource
    @scheme = Scheme.find_by(id: params[:id]) || Scheme.find_by(id: params[:scheme_id])
  end

  def authenticate_scope!
    head :unauthorized and return unless current_user.data_coordinator? || current_user.support?

    if %w[show locations primary_client_group confirm_secondary_client_group secondary_client_group support details check_answers edit_name].include?(action_name) && !((current_user.organisation == @scheme.owning_organisation) || current_user.support?)
      render_not_found and return
    end
  end
end

app/views/schemes/_scheme_list.html.erb
<section class="app-table-group" tabindex="0" aria-labelledby="<%= title.dasherize %>">
  <%= govuk_table do |table| %>
    <%= table.caption(classes: %w[govuk-!-font-size-19 govuk-!-font-weight-regular]) do |caption| %>
    <%= render(SearchResultCaptionComponent.new(searched:, count: pagy.count, item_label:, total_count:, item: "schemes", path: request.path)) %>
      <% end %>
    <%= table.head do |head| %>
      <%= head.row do |row| %>
        <% row.cell(header: true, text: "Code", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Scheme", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Locations", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Support provided by", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Created", html_attributes: {
          scope: "col",
        }) %>
      <% end %>
    <% end %>
    <% @schemes.each do |scheme| %>
      <%= table.body do |body| %>
        <%= body.row do |row| %>
          <% row.cell(text: scheme.id_to_display) %>
          <% row.cell(text: simple_format(scheme_cell(scheme), { class: "govuk-!-font-weight-bold" }, wrapper_tag: "div")) %>
          <% row.cell(text: scheme.locations&.count) %>
          <% row.cell(text: scheme.managing_organisation&.name) %>
          <% row.cell(text: scheme.confirmed? ? scheme.created_at.to_formatted_s(:govuk_date) : govuk_tag(colour: "grey", text: "Incomplete")) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</section>

app/views/schemes/_scheme_summary_list_row.html.erb
<div class="<%= "govuk-summary-list__row #{scheme.confirmed? && attribute[:name] != 'Name' ? 'govuk-summary-list__row--no-actions' : ''}" %>">
    <dt class="govuk-summary-list__key">
        <%= attribute[:name].to_s %>
    </dt>
    <% if scheme.errors[attribute[:id].to_sym].count > 0 %>
        <dd class="govuk-summary-list__value app-summary-list__value--error">
            <p class="govuk-error-message">
                <span class="govuk-error-message govuk-visually-hidden">Error:</span> <%= scheme.errors[attribute[:id].to_sym][0] %>
            </p>
            <%= details_html(attribute) %>
        </dd>
    <% else %>
        <dd class="govuk-summary-list__value">
            <%= details_html(attribute) %>
        </dd>
    <% end %>
    <% if !scheme.confirmed? || attribute[:name] == "Name" %>
        <dd class="govuk-summary-list__actions">
            <a class="govuk-link" href="<%= change_link %>">Change</a>
        </dd>
    <% end %>
</div>

app/views/schemes/check_answers.html.erb
<% content_for :title, "Check your answers before creating this scheme" %>
<%= render partial: "organisations/headings", locals: { main: "Check your changes before creating this scheme", sub: @scheme.service_name } %>

<%= form_for(@scheme, as: :scheme, method: :patch) do |f| %>
  <%= f.govuk_error_summary %>
  <%= govuk_tabs(title: "Check your answers before creating this scheme") do |component| %>
    <% component.tab(label: "Scheme") do %>
      <h2 class="govuk-visually-hidden">Scheme</h2>
      <dl class="govuk-summary-list">
        <% @scheme.check_details_attributes.each do |attr| %>
          <% next if current_user.data_coordinator? && attr[:name] == ("owned by") %>
          <%= render partial: "scheme_summary_list_row", locals: { scheme: @scheme, attribute: attr, change_link: scheme_details_path(@scheme, check_answers: true) } %>
        <% end %>
        <% if !@scheme.arrangement_type_same? %>
        <% @scheme.check_support_services_provider_attributes.each do |attr| %>
          <%= render partial: "scheme_summary_list_row", locals: { scheme: @scheme, attribute: attr, change_link: scheme_support_services_provider_path(@scheme, check_answers: true) } %>
          <% end %>
        <% end %>
        <% @scheme.check_primary_client_attributes.each do |attr| %>
          <%= render partial: "scheme_summary_list_row", locals: { scheme: @scheme, attribute: attr, change_link: scheme_primary_client_group_path(@scheme, check_answers: true) } %>
        <% end %>
        <% @scheme.check_secondary_client_confirmation_attributes.each do |attr| %>
          <%= render partial: "scheme_summary_list_row", locals: { scheme: @scheme, attribute: attr, change_link: scheme_confirm_secondary_client_group_path(@scheme, check_answers: true) } %>
        <% end %>
        <% if @scheme.has_other_client_group == "Yes" %>
          <% @scheme.check_secondary_client_attributes.each do |attr| %>
            <%= render partial: "scheme_summary_list_row", locals: { scheme: @scheme, attribute: attr, change_link: scheme_secondary_client_group_path(@scheme, check_answers: true) } %>
          <% end %>
        <% end %>
        <% @scheme.check_support_attributes.each do |attr| %>
          <%= render partial: "scheme_summary_list_row", locals: { scheme: @scheme, attribute: attr, change_link: scheme_support_path(@scheme, check_answers: true) } %>
        <% end %>
      </dl>
    <% end %>
    <% component.tab(label: "Locations") do %>
      <h2 class="govuk-visually-hidden">Locations</h2>
      <%= govuk_table do |table| %>
        <%= table.caption(classes: %w[govuk-!-font-size-19 govuk-!-font-weight-regular]) do |caption| %>
          <strong><%= @scheme.locations.count %></strong> <%= @scheme.locations.count.eql?(1) ? "location" : "locations" %>
        <% end %>
        <%= table.head do |head| %>
          <%= head.row do |row| %>
            <% row.cell(header: true, text: "Code", html_attributes: {
              scope: "col",
            }) %>
            <% row.cell(header: true, text: "Postcode", html_attributes: {
              scope: "col",
            }) %>
            <% row.cell(header: true, text: "Units", html_attributes: {
              scope: "col",
            }) %>
            <% row.cell(header: true, text: "Common unit type", html_attributes: {
              scope: "col",
            }) %>
            <% row.cell(header: true, text: "Available from", html_attributes: {
              scope: "col",
            }) %>
          <% end %>
        <% end %>
        <% @scheme.locations.each do |location| %>
          <%= table.body do |body| %>
            <%= body.row do |row| %>
              <% row.cell(text: location.id) %>
              <% row.cell(text: simple_format(location_cell(location, "/schemes/#{@scheme.id}/locations/#{location.id}/edit"), { class: "govuk-!-font-weight-bold" }, wrapper_tag: "div")) %>
              <% row.cell(text: location.units) %>
              <% row.cell(text: simple_format("<span>#{location.type_of_unit}</span>")) %>
              <% row.cell(text: location.startdate&.to_formatted_s(:govuk_date)) %>
              <% end %>
          <% end %>
        <% end %>
      <% end %>
      <%= govuk_button_link_to "Add a location", new_location_path(id: @scheme.id), secondary: true %>
    <% end %>
  <% end %>
  <%= f.hidden_field :page, value: "check-answers" %>
  <%= f.hidden_field :confirmed, value: "true" %>
  <% button_label = @scheme.confirmed? ? "Save" : "Create scheme" %>
  <%= f.govuk_submit button_label %>
<% end %>

app/views/schemes/confirm_secondary.html.erb
<% content_for :title, "Does this scheme provide for another client group?" %>

<% content_for :before_content do %>
  <%= govuk_back_link(
    text: "Back",
    href: request.query_parameters["check_answers"] ? "/schemes/#{@scheme.id}/check-answers" : "/schemes/#{@scheme.id}/primary-client-group",
  ) %>
<% end %>

<%= render partial: "organisations/headings", locals: { main: "Does this scheme provide for another client group?", sub: @scheme.service_name } %>

<%= form_for(@scheme, method: :patch) do |f| %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <% selection = [OpenStruct.new(id: "Yes", name: "Yes"), OpenStruct.new(id: "No", name: "No")] %>
      <%= f.govuk_collection_radio_buttons :has_other_client_group,
        selection,
        :id,
        :name,
        legend: nil %>

      <%= f.hidden_field :page, value: "confirm-secondary" %>
      <% if request.query_parameters["check_answers"] == "true" %>
        <%= f.hidden_field :check_answers, value: "true" %>
      <% end %>

      <%= f.govuk_submit "Save and continue" %>
    </div>
  </div>
<% end %>

app/views/schemes/details.html.erb
 <% content_for :title, "Create a new supported housing scheme" %>

<% content_for :before_content do %>
  <%= govuk_back_link(
        text: "Back",
        href: :back,
      ) %>
<% end %>

<%= render partial: "organisations/headings", locals: { main: "Create a new supported housing scheme", sub: nil } %>

<%= form_for(@scheme, method: :patch) do |f| %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_error_summary %>

      <%= f.govuk_text_field :service_name,
                             label: { text: "Scheme name", size: "m" },
                             hint: { text: "This is how you refer to this supported housing scheme within your organisation. For example, the name could relate to the address or location. You’ll be able to see the client group when selecting it." } %>

      <%= f.govuk_check_boxes_fieldset :sensitive,
                                       legend: nil do %>
        <%= f.govuk_check_box :sensitive,
                              1,
                              0,
                              multiple: false,
                              checked: @scheme.sensitive == "Yes",
                              label: { text: "This scheme contains confidential information" } %>
      <% end %>

      <% if current_user.data_coordinator? %>
        <%= f.hidden_field :owning_organisation_id, value: current_user.organisation.id %>
      <% end %>

      <% scheme_types_selection = Scheme.scheme_types.keys.excluding("Missing").map { |key, _| OpenStruct.new(id: key, name: key.to_s.humanize) } %>

      <%= f.govuk_collection_radio_buttons :scheme_type,
                                           scheme_types_selection,
                                           :id,
                                           :name,
                                           legend: { text: "What is this type of scheme?", size: "m" } %>

      <% care_acts_options_hints = { "Yes – part registered as a care home": "A proportion of units are registered as being a care home." } %>

      <% care_acts_options_with_hints = Scheme.registered_under_care_acts.keys.map { |key, _| OpenStruct.new(id: key, name: key.to_s.humanize, description: care_acts_options_hints[key.to_sym]) } %>

      <%= f.govuk_collection_radio_buttons :registered_under_care_act,
                                           care_acts_options_with_hints,
                                           :id,
                                           :name,
                                           :description,
                                           legend: { text: "Is this scheme registered under the Care Standards Act 2000?", size: "m" } %>

      <% organisations = Organisation.all.map { |org| OpenStruct.new(id: org.id, name: org.name) } %>

      <% if current_user.support? %>
        <%= f.govuk_collection_select :owning_organisation_id,
                                      organisations,
                                      :id,
                                      :name,
                                      label: { text: "Which organisation owns the housing stock for this scheme?", size: "m" },
                                      "data-controller": %w[accessible-autocomplete conditional-filter] %>
      <% end %>

      <% mantype_selection = Scheme.arrangement_types.keys.excluding("Missing").map { |key, _| OpenStruct.new(id: key, name: key.to_s.humanize) } %>

      <%= f.govuk_collection_radio_buttons :arrangement_type,
                                           mantype_selection,
                                           :id,
                                           lambda { |option|
                                             if Scheme::ARRANGEMENT_TYPE[option.id] == "D" && !current_user.support?
                                               "Your organisation"
                                             else
                                               option.name
                                             end
                                           },
                                           legend: { text: "Who provides the support services used by this scheme?", size: "m" } %>

      <%= f.hidden_field :page, value: "details" %>
      <% if request.query_parameters["check_answers"] %>
        <%= f.hidden_field :check_answers, value: "true" %>
      <% end %>
      <%= f.govuk_submit "Save and continue" %>
    </div>
  </div>
<% end %>

app/views/schemes/edit_name.html.erb
<% content_for :title, "Scheme details" %>

<% content_for :before_content do %>
  <%= govuk_back_link(
    text: "Back",
    href: :back,
  ) %>
<% end %>

<%= render partial: "organisations/headings", locals: { main: "Scheme details", sub: @scheme.service_name } %>

<%= form_for(@scheme, method: :patch) do |f| %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_error_summary %>

      <%= f.govuk_text_field :service_name,
        label: { text: "Scheme name", size: "m" },
        hint: { text: "This is how you refer to this supported housing scheme within your organisation. For example, the name could relate to the address or location. You’ll be able to see the client group when selecting it." } %>

      <%= f.govuk_check_boxes_fieldset :sensitive,
                                          legend: nil do %>
        <%= f.govuk_check_box :sensitive,
                              1,
                              0,
                              multiple: false,
                              checked: @scheme.sensitive == "Yes",
                              label: { text: "This scheme contains confidential information" } %>
      <% end %>

      <% organisations = Organisation.all.map { |org| OpenStruct.new(id: org.id, name: org.name) } %>

      <% if current_user.support? %>
        <%= f.govuk_collection_select :owning_organisation_id,
                                      organisations,
                                      :id,
                                      :name,
                                      label: { text: "Which organisation owns the housing stock for this scheme?", size: "m" },
                                      "data-controller": %w[accessible-autocomplete conditional-filter] %>
      <% end %>

      <%= f.hidden_field :page, value: "edit-name" %>

      <% if request.query_parameters["check_answers"] %>
        <%= f.hidden_field :check_answers, value: "true" %>
      <% end %>

      <%= f.govuk_submit "Save changes" %>
    </div>
  </div>
<% end %>

app/views/schemes/index.html.erb
<% item_label = format_label(@pagy.count, "scheme") %>
<% title = format_title(@searched, "Supported housing schemes", current_user, item_label, @pagy.count, nil) %>

<% content_for :title, title %>

<%= render partial: "organisations/headings", locals: current_user.support? ? { main: "Supported housing schemes", sub: nil } : { main: "Supported housing schemes", sub: current_user.organisation.name } %>

<%= govuk_button_link_to "Create a new supported housing scheme", new_scheme_path, html: { method: :post } %>

<%= render SearchComponent.new(current_user:, search_label: "Search by scheme name, code or postcode", value: @searched) %>

<hr class="govuk-section-break govuk-section-break--visible govuk-section-break--m">

<%= render partial: "schemes/scheme_list", locals: { schemes: @schemes, title:, pagy: @pagy, searched: @searched, item_label:, total_count: @total_count } %>

<%== render partial: "pagy/nav", locals: { pagy: @pagy, item_name: "schemes" } %>

app/views/schemes/primary_client_group.html.erb
<% content_for :title, "What client group is this scheme intended for?" %>

<% if request.referer&.include?("new") || request.referer&.include?("details") %>
  <% back_button_path = scheme_details_path(@scheme) %>
<% elsif request.referer&.include?("provider") %>
  <% back_button_path = scheme_support_services_provider_path(@scheme) %>
<% elsif request.query_parameters["check_answers"] %>
  <% back_button_path = scheme_check_answers_path(@scheme) %>
<% end %>

<% content_for :before_content do %>
  <%= govuk_back_link(
    text: "Back",
    href: back_button_path,
  ) %>
<% end %>

<%= render partial: "organisations/headings", locals: { main: "What client group is this scheme intended for?", sub: @scheme.service_name } %>

<%= form_for(@scheme, method: :patch) do |f| %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_error_summary %>

      <% primary_client_group_selection = Scheme.primary_client_groups.keys.excluding("Missing").map { |key, _| OpenStruct.new(id: key, name: key) } %>
      <%= f.govuk_collection_radio_buttons :primary_client_group,
        primary_client_group_selection,
        :id,
        :name,
        legend: nil %>

      <%= f.hidden_field :page, value: "primary-client-group" %>
      <% if request.query_parameters["check_answers"] == "true" %>
        <%= f.hidden_field :check_answers, value: "true" %>
      <% end %>
      <% if request.query_parameters["select_managing_org"] == "true" %>
        <%= f.hidden_field :check_answers, value: "true" %>
      <% end %>

      <%= f.govuk_submit "Save and continue" %>
    </div>
  </div>
<% end %>

app/views/schemes/show.html.erb
<% title = @scheme.service_name %>
<% content_for :title, title %>

<% content_for :before_content do %>
  <%= govuk_back_link(
    text: "Back",
    href: "/schemes",
  ) %>
<% end %>

<%= render partial: "organisations/headings", locals: { main: @scheme.service_name, sub: nil } %>

<%= render SubNavigationComponent.new(items: scheme_items(request.path, @scheme.id, "Locations")) %>

<h2 class="govuk-visually-hidden">Scheme</h2>

<%= govuk_summary_list do |summary_list| %>
  <% @scheme.display_attributes.each do |attr| %>
    <% next if current_user.data_coordinator? && attr[:name] == ("Housing stock owned by") %>
    <%= summary_list.row do |row| %>
      <% row.key { attr[:name].eql?("Registered under Care Standards Act 2000") ? "Registered under Care Standards Act 2000" : attr[:name].to_s.humanize } %>
      <% row.value { details_html(attr) } %>
      <% row.action(text: "Change", href: scheme_edit_name_path(scheme_id: @scheme.id)) if attr[:edit] %>
    <% end %>
  <% end %>
<% end %>