config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, {
    path: :account,
    controllers: {
      confirmations: "auth/confirmations",
      passwords: "auth/passwords",
      sessions: "auth/sessions",
      two_factor_authentication: "auth/two_factor_authentication",
    },
    path_names: {
      sign_in: "sign-in",
      sign_out: "sign-out",
      two_factor_authentication: "two-factor-authentication",
      two_factor_authentication_resend_code: "resend-code",
    },
    sign_out_via: %i[get],
  }

  devise_scope :user do
    get "account/password/reset-confirmation", to: "auth/passwords#reset_confirmation"
    get "account/two-factor-authentication/resend", to: "auth/two_factor_authentication#show_resend", as: "user_two_factor_authentication_resend"
    put "account", to: "users#update"
  end

  get "/health", to: ->(_) { [204, {}, [nil]] }

  root to: "start#index"

  get "/accessibility-statement", to: "content#accessibility_statement"
  get "/privacy-notice", to: "content#privacy_notice"
  get "/data-sharing-agreement", to: "content#data_sharing_agreement"

  resource :account, only: %i[show edit], controller: "users" do
    get "edit/password", to: "users#edit_password"
  end

  resources :schemes do
    get "primary-client-group", to: "schemes#primary_client_group"
    get "confirm-secondary-client-group", to: "schemes#confirm_secondary_client_group"
    get "secondary-client-group", to: "schemes#secondary_client_group"
    get "support", to: "schemes#support"
    get "details", to: "schemes#details"
    get "check-answers", to: "schemes#check_answers"
    get "edit-name", to: "schemes#edit_name"
    get "support-services-provider", to: "schemes#support_services_provider"

    member do
      resources :locations do
        get "edit-name", to: "locations#edit_name"
      end
    end
  end

  resources :users do
    member do
      get "deactivate", to: "users#deactivate"
      get "reactivate", to: "users#reactivate"
    end
  end

  resources :organisations do
    member do
      get "details", to: "organisations#details"
      get "users", to: "organisations#users"
      get "users/invite", to: "users/account#new"
      get "logs", to: "organisations#logs"
      get "schemes", to: "organisations#schemes"
    end
  end

  resources :case_logs, path: "/logs" do
    collection do
      post "bulk-upload", to: "bulk_upload#bulk_upload"
      get "bulk-upload", to: "bulk_upload#show"
    end

    member do
      post "form", to: "form#submit_form"
      get "review", to: "form#review"
    end

    FormHandler.instance.forms.each do |_key, form|
      form.pages.map do |page|
        get page.id.to_s.dasherize, to: "form##{page.id}"
      end

      form.subsections.map do |subsection|
        get "#{subsection.id.to_s.dasherize}/check-answers", to: "form#check_answers"
      end
    end
  end

  scope via: :all do
    match "/404", to: "errors#not_found"
    match "/429", to: "errors#too_many_requests", status: 429
    match "/422", to: "errors#unprocessable_entity"
    match "/500", to: "errors#internal_server_error"
  end
end

app/models/case_log.rb
class CaseLogValidator < ActiveModel::Validator
  # Validations methods need to be called 'validate_' to run on model save
  # or form page submission
  include Validations::SetupValidations
  include Validations::HouseholdValidations
  include Validations::PropertyValidations
  include Validations::FinancialValidations
  include Validations::TenancyValidations
  include Validations::DateValidations
  include Validations::LocalAuthorityValidations
  def validate(record)
    validation_methods = public_methods.select { |method| method.starts_with?("validate_") }
    validation_methods.each { |meth| public_send(meth, record) }
  end
end

class CaseLog < ApplicationRecord
  include Validations::SoftValidations
  include DerivedVariables::CaseLogVariables

  has_paper_trail

  validates_with CaseLogValidator
  before_validation :recalculate_start_year!, if: :startdate_changed?
  before_validation :reset_scheme_location!, if: :scheme_changed?, unless: :location_changed?
  before_validation :process_postcode_changes!, if: :postcode_full_changed?
  before_validation :process_previous_postcode_changes!, if: :ppostcode_full_changed?
  before_validation :reset_invalidated_dependent_fields!
  before_validation :reset_location_fields!, unless: :postcode_known?
  before_validation :reset_previous_location_fields!, unless: :previous_postcode_known?
  before_validation :set_derived_fields!
  before_save :update_status!

  belongs_to :owning_organisation, class_name: "Organisation", optional: true
  belongs_to :managing_organisation, class_name: "Organisation", optional: true
  belongs_to :created_by, class_name: "User", optional: true
  belongs_to :scheme, optional: true
  belongs_to :location, optional: true

  scope :filter_by_organisation, ->(org, _user = nil) { where(owning_organisation: org).or(where(managing_organisation: org)) }
  scope :filter_by_status, ->(status, _user = nil) { where status: }
  scope :filter_by_years, lambda { |years, _user = nil|
    first_year = years.shift
    query = filter_by_year(first_year)
    years.each { |year| query = query.or(filter_by_year(year)) }
    query.all
  }
  scope :filter_by_year, ->(year) { where(startdate: Time.zone.local(year.to_i, 4, 1)...Time.zone.local(year.to_i + 1, 4, 1)) }

  scope :filter_by_user, lambda { |selected_user, user|
                           if !selected_user.include?("all") && user.present?
                             where(created_by: user)
                           end
                         }

  scope :filter_by_id, ->(id) { where(id:) }
  scope :filter_by_tenant_code, ->(tenant_code) { where("tenancycode ILIKE ?", "%#{tenant_code}%") }
  scope :filter_by_propcode, ->(propcode) { where("propcode ILIKE ?", "%#{propcode}%") }
  scope :filter_by_postcode, ->(postcode_full) { where("postcode_full ILIKE ?", "%#{postcode_full.gsub(/\s+/, '')}%") }
  scope :search_by, lambda { |param|
                      filter_by_id(param)
                                .or(filter_by_tenant_code(param))
                                .or(filter_by_propcode(param))
                                .or(filter_by_postcode(param))
                    }

  AUTOGENERATED_FIELDS = %w[id status created_at updated_at discarded_at].freeze
  OPTIONAL_FIELDS = %w[first_time_property_let_as_social_housing tenancycode propcode].freeze
  RENT_TYPE_MAPPING_LABELS = { 1 => "Social Rent", 2 => "Affordable Rent", 3 => "Intermediate Rent" }.freeze
  HAS_BENEFITS_OPTIONS = [1, 6, 8, 7].freeze
  STATUS = { "not_started" => 0, "in_progress" => 1, "completed" => 2 }.freeze
  NUM_OF_WEEKS_FROM_PERIOD = { 2 => 26, 3 => 13, 4 => 12, 5 => 50, 6 => 49, 7 => 48, 8 => 47, 9 => 46, 1 => 52 }.freeze
  SUFFIX_FROM_PERIOD = { 2 => "every 2 weeks", 3 => "every 4 weeks", 4 => "every month" }.freeze
  RETIREMENT_AGES = { "M" => 67, "F" => 60, "X" => 67 }.freeze
  enum status: STATUS

  def form
    FormHandler.instance.get_form(form_name) || FormHandler.instance.forms.first.second
  end

  def collection_start_year
    return @start_year if @start_year
    return unless startdate

    window_end_date = Time.zone.local(startdate.year, 4, 1)
    @start_year = startdate < window_end_date ? startdate.year - 1 : startdate.year
  end

  def recalculate_start_year!
    @start_year = nil
    collection_start_year
  end

  def form_name
    return unless startdate

    "#{collection_start_year}_#{collection_start_year + 1}"
  end

  def self.editable_fields
    attribute_names - AUTOGENERATED_FIELDS
  end

  def la
    if location
      location.location_code
    else
      super
    end
  end

  def postcode_full
    if location
      location.postcode
    else
      super
    end
  end

  def completed?
    status == "completed"
  end

  def not_started?
    status == "not_started"
  end

  def in_progress?
    status == "in_progress"
  end

  def weekly_net_income
    return unless earnings && incfreq

    if net_income_is_weekly?
      earnings
    elsif net_income_is_monthly?
      ((earnings * 12) / 52.0).round(0)
    elsif net_income_is_yearly?
      (earnings / 52.0).round(0)
    end
  end

  def weekly_value(field_value)
    num_of_weeks = NUM_OF_WEEKS_FROM_PERIOD[period]
    return unless field_value && num_of_weeks

    (field_value / 52 * num_of_weeks).round(2)
  end

  def weekly_to_value_per_period(field_value)
    num_of_weeks = NUM_OF_WEEKS_FROM_PERIOD[period]

    ((field_value * 52) / num_of_weeks).round(2)
  end

  def applicable_income_range
    return unless ecstat1

    ALLOWED_INCOME_RANGES[ecstat1]
  end

  def first_time_property_let_as_social_housing?
    first_time_property_let_as_social_housing == 1
  end

  def net_income_refused?
    # 2: Tenant prefers not to say
    net_income_known == 2
  end

  def net_income_is_weekly?
    # 1: Weekly
    !!(incfreq && incfreq == 1)
  end

  def net_income_is_monthly?
    # 2: Monthly
    incfreq == 2
  end

  def net_income_is_yearly?
    # 3: Yearly
    incfreq == 3
  end

  def net_income_soft_validation_triggered?
    net_income_in_soft_min_range? || net_income_in_soft_max_range?
  end

  def given_reasonable_preference?
    # 1: Yes
    reasonpref == 1
  end

  def is_renewal?
    # 1: Yes
    renewal == 1
  end

  def is_general_needs?
    # 1: General Needs
    needstype == 1
  end

  def is_supported_housing?
    # 2: Supported Housing
    needstype == 2
  end

  def has_hbrentshortfall?
    # 1: Yes
    hbrentshortfall == 1
  end

  def postcode_known?
    # 1: Yes
    postcode_known == 1
  end

  def previous_postcode_known?
    # 1: Yes
    ppcodenk == 1
  end

  def previous_la_known?
    # 1: Yes
    previous_la_known == 1
  end

  def tshortfall_unknown?
    tshortfall_known == 1
  end

  def is_fixed_term_tenancy?
    [4, 6].include?(tenancy)
  end

  def is_secure_tenancy?
    return unless collection_start_year

    # 1: Secure (including flexible)
    if collection_start_year < 2022
      tenancy == 1
    else
      # 6: Secure - fixed term, 7: Secure - lifetime
      [6, 7].include?(tenancy)
    end
  end

  def is_assured_shorthold_tenancy?
    # 4: Assured Shorthold
    tenancy == 4
  end

  def is_internal_transfer?
    # 1: Internal Transfer
    referral == 1
  end

  def is_relet_to_temp_tenant?
    # 9: Re-let to tenant who occupied same property as temporary accommodation
    rsnvac == 9
  end

  def is_bedsit?
    # 2: Bedsit
    unittype_gn == 2
  end

  def is_shared_housing?
    # 4: Shared flat or maisonette
    # 9: Shared house
    # 10: Shared bungalow
    [4, 9, 10].include?(unittype_gn)
  end

  def has_first_let_vacancy_reason?
    # 15: First let of new-build property
    # 16: First let of conversion, rehabilitation or acquired property
    # 17: First let of leased property
    [15, 16, 17].include?(rsnvac)
  end

  def previous_tenancy_was_temporary?
    # 4: Tied housing or renting with job
    # 6: Supported housing
    # 8: Sheltered accomodation (<= 21/22)
    # 24: Housed by National Asylum Support Service (prev Home Office)
    # 25: Other
    # 34: Specialist retirement housing
    # 35: Extra care housing
    ![4, 6, 8, 24, 25, 34, 35].include?(prevten)
  end

  def armed_forces_regular?
    # 1: Yes – the person is a current or former regular
    !!(armedforces && armedforces == 1)
  end

  def armed_forces_no?
    # 2: No
    armedforces == 2
  end

  def armed_forces_refused?
    # 3: Person prefers not to say / Refused
    armedforces == 3
  end

  def has_pregnancy?
    # 1: Yes
    !!(preg_occ && preg_occ == 1)
  end

  def pregnancy_refused?
    # 3: Tenant prefers not to say / Refused
    preg_occ == 3
  end

  def is_assessed_homeless?
    # 11: Assessed as homeless (or threatened with homelessness within 56 days) by a local authority and owed a homelessness duty
    homeless == 11
  end

  def is_not_homeless?
    # 1: No
    homeless == 1
  end

  def is_london_rent?
    # 2: London Affordable Rent
    # 4: London Living Rent
    rent_type == 2 || rent_type == 4
  end

  def previous_tenancy_was_foster_care?
    # 13: Children's home or foster care
    prevten == 13
  end

  def previous_tenancy_was_refuge?
    # 21: Refuge
    prevten == 21
  end

  def is_reason_permanently_decanted?
    # 1: Permanently decanted from another property owned by this landlord
    reason == 1
  end

  def receives_housing_benefit_only?
    # 1: Housing benefit
    hb == 1
  end

  def benefits_unknown?
    hb == 3
  end

  # Option 8 has been removed starting from 22/23
  def receives_housing_benefit_and_universal_credit?
    # 8: Housing benefit and Universal Credit (without housing element)
    hb == 8
  end

  def receives_uc_with_housing_element_excl_housing_benefit?
    # 6: Universal Credit with housing element (excluding housing benefit)
    hb == 6
  end

  def receives_no_benefits?
    # 9: None
    hb == 9
  end

  def tenant_refuses_to_say_benefits?
    hb == 10
  end

  # Option 7 has been removed starting from 22/23
  def receives_universal_credit_but_no_housing_benefit?

app/controllers/case_logs_controller.rb
class CaseLogsController < ApplicationController
  include Pagy::Backend
  include Modules::CaseLogsFilter
  include Modules::SearchFilter

  skip_before_action :verify_authenticity_token, if: :json_api_request?
  before_action :authenticate, if: :json_api_request?
  before_action :authenticate_user!, unless: :json_api_request?
  before_action :find_resource, except: %i[create index edit]

  def index
    set_session_filters

    all_logs = current_user.case_logs
    unpaginated_filtered_logs = filtered_case_logs(filtered_collection(all_logs, search_term))

    respond_to do |format|
      format.html do
        @pagy, @case_logs = pagy(unpaginated_filtered_logs)
        @searched = search_term.presence
        @total_count = all_logs.size
      end

      format.csv do
        send_data unpaginated_filtered_logs.to_csv, filename: "logs-#{Time.zone.now}.csv"
      end
    end
  end

  def create
    case_log = CaseLog.new(case_log_params)
    respond_to do |format|
      format.html do
        case_log.save!
        redirect_to case_log
      end
      format.json do
        if case_log.save
          render json: case_log, status: :created
        else
          render json: { errors: case_log.errors.messages }, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    if @case_log
      if @case_log.update(api_case_log_params)
        render json: @case_log, status: :ok
      else
        render json: { errors: @case_log.errors.messages }, status: :unprocessable_entity
      end
    else
      render_not_found_json("Log", params[:id])
    end
  end

  def show
    respond_to do |format|
      # We don't have a dedicated non-editable show view
      format.html { edit }
      format.json do
        if @case_log
          render json: @case_log, status: :ok
        else
          render_not_found_json("Log", params[:id])
        end
      end
    end
  end

  def edit
    @case_log = current_user.case_logs.find_by(id: params[:id])
    if @case_log
      render :edit, locals: { current_user: }
    else
      render_not_found
    end
  end

  def destroy
    if @case_log
      if @case_log.delete
        head :no_content
      else
        render json: { errors: @case_log.errors.messages }, status: :unprocessable_entity
      end
    else
      render_not_found_json("Log", params[:id])
    end
  end

private

  API_ACTIONS = %w[create show update destroy].freeze

  def search_term
    params["search"]
  end

  def json_api_request?
    API_ACTIONS.include?(request["action"]) && request.format.json?
  end

  def authenticate
    http_basic_authenticate_or_request_with name: ENV["API_USER"], password: ENV["API_KEY"]
  end

  def case_log_params
    if current_user && !current_user.support?
      org_params.merge(api_case_log_params)
    else
      api_case_log_params
    end
  end

  def org_params
    {
      "owning_organisation_id" => current_user.organisation.id,
      "managing_organisation_id" => current_user.organisation.id,
      "created_by_id" => current_user.id,
    }
  end

  def api_case_log_params
    return {} unless params[:case_log]

    permitted = params.require(:case_log).permit(CaseLog.editable_fields)
    owning_id = permitted["owning_organisation_id"]
    permitted["owning_organisation"] = Organisation.find(owning_id) if owning_id
    permitted
  end

  def find_resource
    @case_log = CaseLog.find_by(id: params[:id])
  end
end

app/views/case_logs/_log_filters.erb
<div class="app-filter-layout__filter">
  <div class="app-filter">
    <div class="app-filter__header">
      <h2 class="govuk-heading-m">Filters</h2>
    </div>
    <div class="app-filter__content">
      <%= form_with html: { method: :get } do |f| %>
        <% years = {"2021": "2021/22", "2022": "2022/23"} %>
        <% all_or_yours = {"all": { label: "All" }, "yours": { label: "Yours" } } %>
        <%= render partial: "filters/checkbox_filter", locals: { f: f, options: years, label: "Collection year", category: "years" } %>
        <%= render partial: "filters/checkbox_filter", locals: { f: f, options: status_filters, label: "Status", category: "status" } %>
        <%= render partial: "filters/radio_filter", locals: { f: f, options: all_or_yours, label: "Logs", category: "user", } %>
        <% if @current_user.support? && request.path == "/logs" %>
          <%= render partial: "filters/radio_filter", locals: {
            f: f,
            options: {
              "all": { label: "All" },
              "specific_org": {
                label: "Specific organisation",
                conditional_filter: {
                  type: "select",
                  label: "Organisation",
                  category: "organisation",
                  options: [OpenStruct.new(id: "", name: "Select an option")] + Organisation.all.map { |org| OpenStruct.new(id: org.id, name: org.name) } 
                }
              }
            },
            label: "Organisation",
            category: "organisation_select"
          } %>
        <% end %>
        <%= f.govuk_submit "Apply filters", class: "govuk-!-margin-bottom-0" %>
      <% end %>
    </div>
  </div>
</div>

app/views/case_logs/_log_list.html.erb
<section class="app-table-group" tabindex="0" aria-labelledby="<%= title.dasherize %>">
  <%= govuk_table do |table| %>
    <%= table.caption(classes: %w[govuk-!-font-size-19 govuk-!-font-weight-regular], id: title.dasherize) do |caption| %>
     <%= render(SearchResultCaptionComponent.new(searched:, count: pagy.count, item_label:, total_count:, item: "logs", path: request.path)) %>
      <%= govuk_link_to "Download (CSV)", "#{request.path}.csv", type: "text/csv" %>
    <% end %>
    <%= table.head do |head| %>
      <%= head.row do |row| %>
        <% row.cell(header: true, text: "Log", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Tenant", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Property", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Tenancy starts", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Log created", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Log status", html_attributes: {
          scope: "col",
        }) %>
        <% if current_user.support? %>
          <% row.cell(header: true, text: "Owning organisation", html_attributes: {
            scope: "col",
          }) %>
          <% row.cell(header: true, text: "Managing organisation", html_attributes: {
            scope: "col",
          }) %>
        <% end %>
      <% end %>
    <% end %>
    <%= table.body do |body| %>
      <% case_logs.map do |log| %>
        <%= body.row do |row| %>
          <% row.cell(header: true, html_attributes: {
            scope: "row",
          }) do %>
            <%= govuk_link_to case_log_path(log) do %>
              <span class="govuk-visually-hidden">Log </span><%= log.id %>
            <% end %>
          <% end %>
          <% row.cell(
            text: log.tenancycode? ? log.tenancycode : "–",
            classes: "app-!-font-tabular",
          ) %>
          <% row.cell(
            text: log.propcode? ? log.propcode : "–",
            classes: "app-!-font-tabular",
          ) %>
          <% row.cell(text: log.startdate.present? ? log.startdate.to_formatted_s(:govuk_date) : "–") %>
          <% row.cell(text: log.created_at.to_formatted_s(:govuk_date)) %>
          <% row.cell do %>
            <%= status_tag(log.status) %>
          <% end %>
          <% if current_user.support? %>
            <% row.cell(text: log.owning_organisation&.name) %>
            <% row.cell(text: log.managing_organisation&.name) %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</section>

app/views/case_logs/_tasklist.html.erb
<ol class="app-task-list govuk-!-margin-top-8">
  <% @case_log.form.sections.map do |section| %>
    <li>
      <h2 class="app-task-list__section-heading">
        <%= section.label %>
      </h2>
      <% if section.description %>
        <p class="govuk-body"><%= section.description.html_safe %></p>
      <% end %>
      <ul class="app-task-list__items">
        <% section.subsections.map do |subsection| %>
          <% if subsection.applicable_questions(@case_log).count > 0 || !subsection.enabled?(@case_log) %>
            <% subsection_status = subsection.status(@case_log) %>
            <li class="app-task-list__item">
              <span class="app-task-list__task-name" id="<%= subsection.id.dasherize %>">
                <%= subsection_link(subsection, @case_log, current_user) %>
              </span>
              <%= status_tag(subsection_status, "app-task-list__tag") %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </li>
  <% end %>
</ol>

app/views/case_logs/bulk_upload.html.erb
<% content_for :title, "Bulk upload" %>

<%= form_for @bulk_upload, url: bulk_upload_case_logs_path, method: "post" do |f| %>
  <%= f.govuk_error_summary %>

  <%= f.govuk_file_field :case_log_bulk_upload,
      label: { text: content_for(:title), size: "l" },
      hint: { text: "Upload a spreadsheet using the template" } %>

  <%= f.govuk_submit "Upload" %>
<% end %>

app/views/case_logs/edit.html.erb
<% content_for :title, "Log #{@case_log.id}" %>
<% content_for :breadcrumbs, govuk_breadcrumbs(breadcrumbs: {
  "Logs" => "/logs",
  content_for(:title) => "",
}) %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds-from-desktop">
    <h1 class="govuk-heading-xl">
      <%= content_for(:title) %>
    </h1>

    <% if @case_log.status == "in_progress" %>
      <p class="govuk-body govuk-!-margin-bottom-7"><%= get_subsections_count(@case_log, :completed) %> of <%= get_subsections_count(@case_log, :all) %> sections completed.</p>
      <p class="govuk-body govuk-!-margin-bottom-2">
        <% next_incomplete_section = get_next_incomplete_section(@case_log) %>
      </p>
      <p>
        <% if next_incomplete_section.present? %>
          <a class="app-section-skip-link" href="#<%= next_incomplete_section.id.dasherize %>">
            Skip to next incomplete section: <%= next_incomplete_section.label %>
          </a>
        <% end %>
      </p>
    <% elsif @case_log.status == "not_started" %>
      <p class="govuk-body">This log has not been started.</p>
    <% elsif @case_log.status == "completed" %>
      <p class="govuk-body">
        <%= status_tag(@case_log.status) %>
      </p>
      <p class="govuk-body">
        You can <%= govuk_link_to "review and make changes to this log", "/logs/#{@case_log.id}/review" %> up to 3 months after the end of the current collection year, which closes on 31 March <%= @case_log.collection_start_year.present? ? @case_log.collection_start_year + 1 : "" %>.
      </p>
    <% end %>
    <%= render "tasklist" %>
  </div>
</div>

app/views/case_logs/index.html.erb
<% item_label = format_label(@pagy.count, "log") %>
<% title = format_title(@searched, "Logs", current_user, item_label, @pagy.count, nil) %>

<% content_for :title, title %>

<%= render partial: "organisations/headings", locals: current_user.support? ? { main: "Logs", sub: nil } : { main: "Logs", sub: current_user.organisation.name } %>

<div class="app-filter-layout" data-controller="filter-layout">
  <div class="govuk-button-group app-filter-toggle">
    <%= govuk_button_to "Create a new lettings log", case_logs_path %>
    <%#= govuk_link_to "Upload logs", bulk_upload_case_logs_path %>
  </div>

  <%= render partial: "log_filters" %>
  <div class="app-filter-layout__content">
    <%= render SearchComponent.new(current_user:, search_label: "Search by log ID, tenant code, property reference or postcode", value: @searched) %>
    <%= govuk_section_break(visible: true, size: "m") %>
    <%= render partial: "log_list", locals: { case_logs: @case_logs, title: "Logs", pagy: @pagy, searched: @searched, item_label:, total_count: @total_count } %>
    <%== render partial: "pagy/nav", locals: { pagy: @pagy, item_name: "logs" } %>
  </div>
</div>