config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, {
    path: :account,
    controllers: {
      confirmations: "auth/confirmations",
      passwords: "auth/passwords",
      sessions: "auth/sessions",
      two_factor_authentication: "auth/two_factor_authentication",
    },
    path_names: {
      sign_in: "sign-in",
      sign_out: "sign-out",
      two_factor_authentication: "two-factor-authentication",
      two_factor_authentication_resend_code: "resend-code",
    },
    sign_out_via: %i[get],
  }

  devise_scope :user do
    get "account/password/reset-confirmation", to: "auth/passwords#reset_confirmation"
    get "account/two-factor-authentication/resend", to: "auth/two_factor_authentication#show_resend", as: "user_two_factor_authentication_resend"
    put "account", to: "users#update"
  end

  get "/health", to: ->(_) { [204, {}, [nil]] }

  root to: "start#index"

  get "/accessibility-statement", to: "content#accessibility_statement"
  get "/privacy-notice", to: "content#privacy_notice"
  get "/data-sharing-agreement", to: "content#data_sharing_agreement"

  resource :account, only: %i[show edit], controller: "users" do
    get "edit/password", to: "users#edit_password"
  end

  resources :schemes do
    get "primary-client-group", to: "schemes#primary_client_group"
    get "confirm-secondary-client-group", to: "schemes#confirm_secondary_client_group"
    get "secondary-client-group", to: "schemes#secondary_client_group"
    get "support", to: "schemes#support"
    get "details", to: "schemes#details"
    get "check-answers", to: "schemes#check_answers"
    get "edit-name", to: "schemes#edit_name"
    get "support-services-provider", to: "schemes#support_services_provider"

    member do
      resources :locations do
        get "edit-name", to: "locations#edit_name"
      end
    end
  end

  resources :users do
    member do
      get "deactivate", to: "users#deactivate"
      get "reactivate", to: "users#reactivate"
    end
  end

  resources :organisations do
    member do
      get "details", to: "organisations#details"
      get "users", to: "organisations#users"
      get "users/invite", to: "users/account#new"
      get "logs", to: "organisations#logs"
      get "schemes", to: "organisations#schemes"
    end
  end

  resources :case_logs, path: "/logs" do
    collection do
      post "bulk-upload", to: "bulk_upload#bulk_upload"
      get "bulk-upload", to: "bulk_upload#show"
    end

    member do
      post "form", to: "form#submit_form"
      get "review", to: "form#review"
    end

    FormHandler.instance.forms.each do |_key, form|
      form.pages.map do |page|
        get page.id.to_s.dasherize, to: "form##{page.id}"
      end

      form.subsections.map do |subsection|
        get "#{subsection.id.to_s.dasherize}/check-answers", to: "form#check_answers"
      end
    end
  end

  scope via: :all do
    match "/404", to: "errors#not_found"
    match "/429", to: "errors#too_many_requests", status: 429
    match "/422", to: "errors#unprocessable_entity"
    match "/500", to: "errors#internal_server_error"
  end
end

app/models/form/setup/pages/organisation.rb
class Form::Setup::Pages::Organisation < ::Form::Page
  def initialize(id, hsh, subsection)
    super
    @id = "organisation"
    @header = ""
    @description = ""
    @questions = questions
    @subsection = subsection
  end

  def questions
    [
      Form::Setup::Questions::OwningOrganisationId.new(nil, nil, self),
    ]
  end

  def routed_to?(_case_log, current_user)
    !!current_user&.support?
  end
end

app/models/organisation.rb
class Organisation < ApplicationRecord
<<<<<<< HEAD
  has_many :users, dependent: :delete_all
  has_many :owned_case_logs, class_name: "CaseLog", foreign_key: "owning_organisation_id", dependent: :delete_all
  has_many :managed_case_logs, class_name: "CaseLog", foreign_key: "managing_organisation_id"
  has_many :data_protection_confirmations
  has_many :organisation_rent_periods

  has_many :owned_schemes, class_name: "Scheme", foreign_key: "owning_organisation_id", dependent: :delete_all
  has_many :managed_schemes, class_name: "Scheme", foreign_key: "managing_organisation_id"
=======
  has_many :users, dependent: :destroy
  has_many :owned_case_logs, class_name: "CaseLog", foreign_key: "owning_organisation_id", dependent: :destroy
  has_many :managed_case_logs, class_name: "CaseLog", foreign_key: "managing_organisation_id", dependent: :destroy
  has_many :data_protection_confirmations
  has_many :organisation_rent_periods
  has_many :owned_schemes, class_name: "Scheme", foreign_key: "stock_owning_organisation_id", dependent: :destroy
  has_many :managed_schemes, class_name: "Scheme", dependent: :destroy
>>>>>>> 8120be4f (added cascading delete to models)

  scope :search_by_name, ->(name) { where("name ILIKE ?", "%#{name}%") }
  scope :search_by, ->(param) { search_by_name(param) }

  has_paper_trail

  PROVIDER_TYPE = {
    LA: 1,
    PRP: 2,
  }.freeze

  enum provider_type: PROVIDER_TYPE

  validates :name, presence: { message: I18n.t("validations.organisation.name_missing") }
  validates :provider_type, presence: { message: I18n.t("validations.organisation.provider_type_missing") }

  def case_logs
    CaseLog.filter_by_organisation(self)
  end

  def completed_case_logs
    case_logs.completed
  end

  def not_completed_case_logs
    case_logs.not_completed
  end

  def address_string
    %i[address_line1 address_line2 postcode].map { |field| public_send(field) }.join("\n")
  end

  def rent_periods
    organisation_rent_periods.pluck(:rent_period)
  end

  def rent_period_labels
    labels = rent_periods.map { |period| RentPeriod.rent_period_mappings[period.to_s]["value"] }
    labels.presence || %w[All]
  end

  def data_protection_confirmed?
    !!data_protection_confirmations.order(created_at: :desc).first&.confirmed
  end

  def data_protection_agreement_string
    data_protection_confirmed? ? "Accepted" : "Not accepted"
  end

  DISPLAY_PROVIDER_TYPE = { "LA": "Local authority", "PRP": "Private registered provider" }.freeze

  def display_provider_type
    DISPLAY_PROVIDER_TYPE[provider_type.to_sym]
  end

  def display_attributes
    [
      { name: "name", value: name, editable: true },
      { name: "address", value: address_string, editable: true },
      { name: "telephone_number", value: phone, editable: true },
      { name: "type", value: display_provider_type, editable: false },
      { name: "rent_periods", value: rent_period_labels, editable: false, format: :bullet },
      { name: "Owns housing stock", value: holds_own_stock ? "Yes" : "No", editable: false },
      { name: "other_stock_owners", value: other_stock_owners, editable: false },
      { name: "managing_agents", value: managing_agents, editable: false },
      { name: "data_protection_agreement", value: data_protection_agreement_string, editable: false },
    ]
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  include Pagy::Backend
  include Modules::CaseLogsFilter
  include Modules::SearchFilter

  before_action :authenticate_user!
  before_action :find_resource, except: %i[index new create]
  before_action :authenticate_scope!, except: [:index]

  def index
    redirect_to organisation_path(current_user.organisation) unless current_user.support?

    all_organisations = Organisation.order(:name)
    @pagy, @organisations = pagy(filtered_collection(all_organisations, search_term))
    @searched = search_term.presence
    @total_count = all_organisations.size
  end

  def schemes
    all_schemes = Scheme.where(owning_organisation: @organisation)

    @pagy, @schemes = pagy(filtered_collection(all_schemes, search_term))
    @searched = search_term.presence
    @total_count = all_schemes.size
  end

  def show
    redirect_to details_organisation_path(@organisation)
  end

  def users
    organisation_users = @organisation.users.sorted_by_organisation_and_role
    unpaginated_filtered_users = filtered_collection(organisation_users, search_term)

    respond_to do |format|
      format.html do
        @pagy, @users = pagy(unpaginated_filtered_users)
        @searched = search_term.presence
        @total_count = @organisation.users.size

        if current_user.support?
          render "users", layout: "application"
        else
          render "users/index"
        end
      end
      format.csv do
        send_data unpaginated_filtered_users.to_csv, filename: "users-#{@organisation.name}-#{Time.zone.now}.csv"
      end
    end
  end

  def details
    render "show"
  end

  def new
    @resource = Organisation.new
    render "new", layout: "application"
  end

  def create
    @resource = Organisation.new(org_params)
    if @resource.save
      redirect_to organisations_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    if current_user.data_coordinator? || current_user.support?
      render "edit", layout: "application"
    else
      head :unauthorized
    end
  end

  def update
    if current_user.data_coordinator? || current_user.support?
      if @organisation.update(org_params)
        flash[:notice] = I18n.t("organisation.updated")
        redirect_to details_organisation_path(@organisation)
      end
    else
      head :unauthorized
    end
  end

  def logs
    if current_user.support?
      set_session_filters(specific_org: true)

      organisation_logs = CaseLog.all.where(owning_organisation_id: @organisation.id)
      unpaginated_filtered_logs = filtered_case_logs(filtered_collection(organisation_logs, search_term))

      respond_to do |format|
        format.html do
          @pagy, @case_logs = pagy(unpaginated_filtered_logs)
          @searched = search_term.presence
          @total_count = organisation_logs.size
          render "logs", layout: "application"
        end

        format.csv do
          send_data unpaginated_filtered_logs.to_csv, filename: "logs-#{@organisation.name}-#{Time.zone.now}.csv"
        end
      end
    else
      redirect_to(case_logs_path)
    end
  end

private

  def org_params
    params.require(:organisation).permit(:name, :address_line1, :address_line2, :postcode, :phone, :holds_own_stock, :provider_type, :housing_registration_no)
  end

  def search_term
    params["search"]
  end

  def authenticate_scope!
    if %w[create new].include? action_name
      head :unauthorized and return unless current_user.support?
    elsif current_user.organisation != @organisation && !current_user.support?
      render_not_found
    end
  end

  def find_resource
    @organisation = Organisation.find(params[:id])
  end
end

app/helpers/organisation_helper.rb
module OrganisationHelper
  def organisation_header(path, user, current_organisation)
    if path == "/organisations"
      "Organisations"
    elsif user.organisation_id == current_organisation.id
      "Your organisation"
    else
      current_organisation.name
    end
  end
end

app/views/organisations/_headings.html.erb
<h1 class="govuk-heading-l">
  <span class="govuk-caption-l"><%= sub %></span>
  <%= main %>
</h1>

app/views/organisations/_organisation_list.html.erb
<section class="app-table-group" tabindex="0" aria-labelledby="<%= title.dasherize %>">
  <%= govuk_table do |table| %>
    <%= table.caption(classes: %w[govuk-!-font-size-19 govuk-!-font-weight-regular]) do |caption| %>
      <%= render(SearchResultCaptionComponent.new(searched:, count: pagy.count, item_label:, total_count:, item: "organisations", path: request.path)) %>
    <% end %>
    <%= table.head do |head| %>
      <%= head.row do |row| %>
        <% row.cell(header: true, text: "Name", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Registration number", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Type", html_attributes: {
          scope: "col",
        }) %>
      <% end %>
    <% end %>
    <% @organisations.each do |organisation| %>
      <%= table.body do |body| %>
        <%= body.row do |row| %>
          <% row.cell(header: true, html_attributes: {
            scope: "row",
          }) do %>
            <%= govuk_link_to(organisation.name, "organisations/#{organisation.id}/logs") %>
          <% end %>
          <% row.cell(text: organisation.housing_registration_no) %>
          <% row.cell(text: organisation.display_provider_type) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</section>

app/views/organisations/_users.html.erb
<%= govuk_table do |table| %>
  <%= table.head do |head| %>
    <%= head.row do |row|
      row.cell(header: true, text: "Name and email adress")
      row.cell(header: true, text: "Organisation and role")
      row.cell(header: true, text: "Last logged in")
    end %>
  <% end %>
  <% @organisation.users.each do |user| %>
    <%= table.body do |body| %>
      <%= body.row do |row|
        row.cell(text: simple_format(user.name_email_display, {}, wrapper_tag: "div"))
        row.cell(text: simple_format(user.org_role_display, {}, wrapper_tag: "div"))
        row.cell(text: user.last_sign_in_at_display )
      end %>
    <% end %>
  <% end %>
<% end %>

app/views/organisations/details.html.erb
<%= govuk_summary_list do |summary_list| %>
  <% @organisation.display_attributes.each do |attr, val| %>
    <%= summary_list.row do |row|
      row.key { attr.to_s.humanize }
      row.value { simple_format(val, {}, wrapper_tag: "div") }
    end %>
  <% end %>
<% end %>

app/views/organisations/edit.html.erb
<% content_for :title, "Change #{@organisation.name}’s details" %>

<% content_for :before_content do %>
  <%= govuk_back_link(href: :back) %>
<% end %>

<%= form_for(@organisation, as: :organisation, html: { method: :patch }) do |f| %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h1 class="govuk-heading-l">
        <%= content_for(:title) %>
      </h1>

      <%= f.govuk_text_field :name,
        autocomplete: "name" %>

      <%= f.govuk_text_field :address_line1,
        label: { text: "Address line 1" },
        autocomplete: "address-line1" %>

      <%= f.govuk_text_field :address_line2,
        label: { text: "Address line 2" },
        autocomplete: "address-line2" %>

      <%= f.govuk_text_field :postcode,
        autocomplete: "postal-code",
        width: 10 %>

      <%= f.govuk_phone_field :phone,
        label: { text: "Telephone number" },
        autocomplete: "tel",
        width: 20 %>

      <%= f.govuk_submit "Save changes" %>
    </div>
  </div>
<% end %>

app/views/organisations/index.html.erb
<% item_label = format_label(@pagy.count, "organisation") %>
<% title = format_title(@searched, "Organisations", current_user, item_label, @pagy.count, nil) %>

<% content_for :title, title %>

<%= render partial: "organisations/headings", locals: request.path == "/organisations" ? { main: "Organisations", sub: nil } : { main: @organisation.name, sub: "Organisations" } %>

<% if current_user.support? %>
  <%= govuk_button_link_to "Create a new organisation", new_organisation_path, html: { method: :get } %>
<% end %>

<%= render SearchComponent.new(current_user:, search_label: "Search by organisation name", value: @searched) %>

<%= govuk_section_break(visible: true, size: "m") %>

<%= render partial: "organisation_list", locals: { organisations: @organisations, title: "Organisations", pagy: @pagy, searched: @searched, item_label:, total_count: @total_count } %>
<%== render partial: "pagy/nav", locals: { pagy: @pagy, item_name: "organisations" } %>

app/views/organisations/logs.erb
<% content_for :title, "Logs" %>

<h1 class="govuk-heading-l">
  <span class="govuk-caption-l"><%= @organisation.name %></span>
  <%= content_for(:title) %>
</h1>
<div class="govuk-!-margin-bottom-4">
  <%= render NavigationComponent.new(
      items: secondary_items(request.path, @organisation.id),
      level: "sub"
    ) %>
</div>
<div class="app-filter-layout" data-controller="filter-layout">

  <%= render partial: "case_logs/log_filters" %>
  <% if @case_logs.present? %>
    <div class="app-filter-layout__content">
      <%= render partial: "case_logs/log_list", locals: { case_logs: @case_logs, title: "Logs", pagy: @pagy } %>
      <%== render partial: "pagy/nav", locals: { pagy: @pagy, item_name: "logs" } %>
    </div>
  <% end %>
</div>

app/views/organisations/logs.html.erb
<% item_label = format_label(@pagy.count, "log") %>
<% title = format_title(@searched, "Logs", current_user, item_label, @pagy.count, @organisation.name) %>

<% content_for :title, title %>

<%= render partial: "organisations/headings", locals: { main: @organisation.name, sub: nil } %>

<% if current_user.support? %>
  <%= render SubNavigationComponent.new(
    items: secondary_items(request.path, @organisation.id),
  ) %>
  <h2 class="govuk-visually-hidden">Logs</h2>
<% end %>

<div class="app-filter-layout" data-controller="filter-layout">
  <div class="govuk-button-group app-filter-toggle">
    <%= govuk_button_to "Create a new lettings log for this organisation", case_logs_path(case_log: { owning_organisation_id: @organisation.id }, method: :post) %>
  </div>

  <%= render partial: "case_logs/log_filters" %>
  <div class="app-filter-layout__content">
    <%= render SearchComponent.new(current_user:, search_label: "Search by log ID, tenant code, property reference or postcode", value: @searched) %>
    <%= govuk_section_break(visible: true, size: "m") %>
    <%= render partial: "case_logs/log_list", locals: { case_logs: @case_logs, title: "Logs", pagy: @pagy, searched: @searched, item_label:, total_count: @total_count } %>
    <%== render partial: "pagy/nav", locals: { pagy: @pagy, item_name: "logs" } %>
  </div>
</div>

app/views/organisations/new.html.erb
<% content_for :title, "Create a new organisation" %>

<% content_for :before_content do %>
  <%= govuk_back_link(href: :back) %>
<% end %>

<%= form_for(@resource, as: :organisation, html: { method: :post }) do |f| %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_error_summary %>

      <h1 class="govuk-heading-l">
        <%= content_for(:title) %>
      </h1>

      <%= f.govuk_text_field :name,
        label: { size: "m" },
        autocomplete: "name" %>

      <%= f.govuk_text_field :address_line1,
        label: { text: "Address line 1", size: "m" },
        autocomplete: "address-line1" %>

      <%= f.govuk_text_field :address_line2,
        label: { text: "Address line 2", size: "m" },
        autocomplete: "address-line2" %>

      <%= f.govuk_text_field :postcode,
        label: { size: "m" },
        autocomplete: "postal-code",
        width: 10 %>

      <%= f.govuk_phone_field :phone,
        label: { text: "Telephone number", size: "m" },
        autocomplete: "tel",
        width: 20 %>

      <%= f.govuk_text_field :housing_registration_no,
        label: { text: "Regulator of Social Housing registration number", size: "m" },
        width: 10 %>

      <% null_option = [OpenStruct.new(id: "", name: "Select an option")] %>
      <% types = Organisation::PROVIDER_TYPE.map { |key, _val| OpenStruct.new(id: key, name: Organisation::DISPLAY_PROVIDER_TYPE[key]) } %>
      <% type_answer_options = null_option + types %>

      <%= f.govuk_collection_select :provider_type,
        type_answer_options,
        :id,
        :name,
        label: { text: "Organisation type", size: "m" },
        options: { disabled: [""], selected: @resource.provider_type || "" } %>

      <%= f.govuk_collection_radio_buttons :holds_own_stock,
        [OpenStruct.new(id: true, name: "Yes"), OpenStruct.new(id: false, name: "No")],
        :id,
        :name,
        legend: { text: "Does the organisation hold its own stock?", size: "m" } %>

      <%= f.govuk_submit "Create organisation" %>
    </div>
  </div>
<% end %>

app/views/organisations/schemes.html.erb
<% item_label = format_label(@pagy.count, "scheme") %>
<% title = format_title(@searched, "Supported housing schemes", current_user, item_label, @pagy.count, @organisation.name) %>

<% content_for :title, title %>

<%= render partial: "organisations/headings", locals: current_user.support? ? { main: @organisation.name, sub: nil } : { main: "Supported housing schemes", sub: current_user.organisation.name } %>

<% if current_user.support? %>
  <%= render SubNavigationComponent.new(
    items: secondary_items(request.path, @organisation.id),
  ) %>
  <h2 class="govuk-visually-hidden">Supported housing schemes</h2>
<% end %>

<%= govuk_button_link_to "Create a new supported housing scheme", new_scheme_path, html: { method: :post } %>

<%= govuk_details(
  classes: "govuk-!-width-two-thirds",
  summary_text: "What is a supported housing scheme?",
  text: "A supported housing scheme (also known as a ‘supported housing service’) provides shared or self-contained housing for a particular client group, for example younger or vulnerable people. A single scheme can contain multiple units, for example bedrooms in shared houses or a bungalow with 3 bedrooms.",
) %>

<%= render SearchComponent.new(current_user:, search_label: "Search by scheme name, code or postcode", value: @searched) %>

<hr class="govuk-section-break govuk-section-break--visible govuk-section-break--m">

<%= render partial: "schemes/scheme_list", locals: { schemes: @schemes, title:, pagy: @pagy, searched: @searched, item_label:, total_count: @total_count } %>

<%== render partial: "pagy/nav", locals: { pagy: @pagy, item_name: "schemes" } %>

app/views/organisations/show.html.erb
<% title = current_user.support? ? "#{@organisation.name} (Organisation details)" : "Organisation details" %>
<% title = format_title(nil, current_user.support? ? "About this organisation" : "About your organisation", current_user, nil, nil, @organisation.name) %>
<% content_for :title, title %>

<%= render partial: "organisations/headings", locals: current_user.support? ? { main: @organisation.name, sub: nil } : { main: "About your organisation", sub: current_user.organisation.name } %>

<% if current_user.support? %>
  <%= render SubNavigationComponent.new(
    items: secondary_items(request.path, @organisation.id),
  ) %>
  <h2 class="govuk-visually-hidden">About this organisation</h2>
<% end %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds-from-desktop">
    <%= govuk_summary_list do |summary_list| %>
      <% @organisation.display_attributes.each do |attr| %>
        <% if can_edit_org?(current_user) && attr[:editable] %>
          <%= summary_list.row do |row| %>
            <% row.key { attr[:name].to_s.humanize } %>
            <% row.value { details_html(attr) } %>
            <% row.action(
              visually_hidden_text: attr[:name].to_s.humanize.downcase,
              href: edit_organisation_path,
              html_attributes: { "data-qa": "change-#{attr[:name]}" },
            ) %>
          <% end %>
        <% else %>
          <%= summary_list.row do |row| %>
            <% row.key { attr[:name].to_s.humanize } %>
            <% row.value { details_html(attr) } %>
            <% row.action %>
          <% end %>
        <% end %>

      <% end %>
    <% end %>
  </div>

  <div class="govuk-grid-column-one-third-from-desktop">
    <%= render partial: "layouts/collection_resources" %>
  </div>
</div>

app/views/organisations/users.html.erb
<% item_label = format_label(@pagy.count, "user") %>
<% title = format_title(@searched, "Users", current_user, item_label, @pagy.count, @organisation.name) %>

<% content_for :title, title %>

<%= render partial: "organisations/headings", locals: { main: @organisation.name, sub: nil } %>

<% if current_user.support? %>
  <%= render SubNavigationComponent.new(
    items: secondary_items(request.path, @organisation.id),
  ) %>
  <h2 class="govuk-visually-hidden">Users</h2>
<% end %>

<% if current_user.data_coordinator? || current_user.support? %>
  <%= govuk_button_link_to "Invite user", new_user_path(organisation_id: @organisation.id), html: { method: :get } %>
<% end %>

<%= render SearchComponent.new(current_user:, search_label: "Search by name or email address", value: @searched) %>

<%= govuk_section_break(visible: true, size: "m") %>

<%= render partial: "users/user_list", locals: { users: @users, title:, pagy: @pagy, searched: @searched, item_label:, total_count: @total_count } %>
<%== render partial: "pagy/nav", locals: { pagy: @pagy, item_name: "users" } %>