config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, {
    path: :account,
    controllers: {
      confirmations: "auth/confirmations",
      passwords: "auth/passwords",
      sessions: "auth/sessions",
      two_factor_authentication: "auth/two_factor_authentication",
    },
    path_names: {
      sign_in: "sign-in",
      sign_out: "sign-out",
      two_factor_authentication: "two-factor-authentication",
      two_factor_authentication_resend_code: "resend-code",
    },
    sign_out_via: %i[get],
  }

  devise_scope :user do
    get "account/password/reset-confirmation", to: "auth/passwords#reset_confirmation"
    get "account/two-factor-authentication/resend", to: "auth/two_factor_authentication#show_resend", as: "user_two_factor_authentication_resend"
    put "account", to: "users#update"
  end

  get "/health", to: ->(_) { [204, {}, [nil]] }

  root to: "start#index"

  get "/accessibility-statement", to: "content#accessibility_statement"
  get "/privacy-notice", to: "content#privacy_notice"
  get "/data-sharing-agreement", to: "content#data_sharing_agreement"

  resource :account, only: %i[show edit], controller: "users" do
    get "edit/password", to: "users#edit_password"
  end

  resources :schemes do
    get "primary-client-group", to: "schemes#primary_client_group"
    get "confirm-secondary-client-group", to: "schemes#confirm_secondary_client_group"
    get "secondary-client-group", to: "schemes#secondary_client_group"
    get "support", to: "schemes#support"
    get "details", to: "schemes#details"
    get "check-answers", to: "schemes#check_answers"
    get "edit-name", to: "schemes#edit_name"
    get "support-services-provider", to: "schemes#support_services_provider"

    member do
      resources :locations do
        get "edit-name", to: "locations#edit_name"
      end
    end
  end

  resources :users do
    member do
      get "deactivate", to: "users#deactivate"
      get "reactivate", to: "users#reactivate"
    end
  end

  resources :organisations do
    member do
      get "details", to: "organisations#details"
      get "users", to: "organisations#users"
      get "users/invite", to: "users/account#new"
      get "logs", to: "organisations#logs"
      get "schemes", to: "organisations#schemes"
    end
  end

  resources :case_logs, path: "/logs" do
    collection do
      post "bulk-upload", to: "bulk_upload#bulk_upload"
      get "bulk-upload", to: "bulk_upload#show"
    end

    member do
      post "form", to: "form#submit_form"
      get "review", to: "form#review"
    end

    FormHandler.instance.forms.each do |_key, form|
      form.pages.map do |page|
        get page.id.to_s.dasherize, to: "form##{page.id}"
      end

      form.subsections.map do |subsection|
        get "#{subsection.id.to_s.dasherize}/check-answers", to: "form#check_answers"
      end
    end
  end

  scope via: :all do
    match "/404", to: "errors#not_found"
    match "/429", to: "errors#too_many_requests", status: 429
    match "/422", to: "errors#unprocessable_entity"
    match "/500", to: "errors#internal_server_error"
  end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
protected

  def after_confirmation_path_for(_resource_name, resource)
    new_user_confirmation_path(resource)
  end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  include Helpers::Email

  def reset_confirmation
    self.resource = resource_class.new
    @email = params["email"]
    if @email.empty?
      resource.errors.add :email, "Enter an email address"
      render "devise/passwords/new", status: :unprocessable_entity
    elsif !email_valid?(@email)
      resource.errors.add :email, "Enter an email address in the correct format, like name@example.com"
      render "devise/passwords/new", status: :unprocessable_entity
    else
      render "devise/passwords/reset_confirmation"
    end
  end

  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
  end

  def edit
    super
    render "users/reset_password"
  end

protected

  def after_sending_reset_password_instructions_path_for(_resource)
    password_reset_path(email: params.dig("user", "email"))
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  include Helpers::Email

  def create
    self.resource = resource_class.new
    if params.dig("user", "email").empty?
      resource.errors.add :email, "Enter an email address"
    elsif !email_valid?(params.dig("user", "email"))
      resource.errors.add :email, "Enter an email address in the correct format, like name@example.com"
    end
    if params.dig("user", "password").empty?
      resource.errors.add :password, "Enter a password"
    end
    if resource.errors.present?
      render :new, status: :unprocessable_entity
    else
      super
    end
  end

private

  def after_sign_in_path_for(resource)
    params.dig("user", "start").present? ? case_logs_path : super
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include Helpers::Email

  def reset_confirmation
    self.resource = resource_class.new
    @email = params["email"]
    if @email.empty?
      resource.errors.add :email, "Enter an email address"
      render "devise/passwords/new", status: :unprocessable_entity
    elsif !email_valid?(@email)
      resource.errors.add :email, "Enter an email address in the correct format, like name@example.com"
      render "devise/passwords/new", status: :unprocessable_entity
    else
      flash[:notice] = "Reset password instructions have been sent to #{@email}"
      render "devise/confirmations/reset"
    end
  end

  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
  end

protected

  def after_sending_reset_password_instructions_path_for(_resource)
    confirmations_reset_path(email: params.dig("user", "email"))
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include Helpers::Email

  def create
    self.resource = resource_class.new
    if params.dig("user", "email").empty?
      resource.errors.add :email, "Enter an email address"
    elsif !email_valid?(params.dig("user", "email"))
      resource.errors.add :email, "Enter an email address in the correct format, like name@example.com"
    end
    if params.dig("user", "password").empty?
      resource.errors.add :password, "Enter a password"
    end
    if resource.errors.present?
      render :new, status: :unprocessable_entity
    else
      super
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pagy::Backend
  include Devise::Controllers::SignInOut
  include Helpers::Email
  include Modules::SearchFilter
  before_action :authenticate_user!
  before_action :find_resource, except: %i[new create]
  before_action :authenticate_scope!, except: %i[new]

  def index
    redirect_to users_organisation_path(current_user.organisation) unless current_user.support?

    all_users = User.sorted_by_organisation_and_role
    filtered_users = filtered_users(all_users, search_term)
    @pagy, @users = pagy(filtered_users)
    @searched = search_term.presence
    @total_count = all_users.size

    respond_to do |format|
      format.html
      format.csv do
        if current_user.support?
          send_data filtered_users.to_csv, filename: "users-#{Time.zone.now}.csv"
        else
          head :unauthorized
        end
      end
    end
  end

  def show; end

  def edit
    redirect_to user_path(@user) unless @user.active?
  end

  def update
    if @user.update(user_params)
      if @user == current_user
        bypass_sign_in @user
        flash[:notice] = I18n.t("devise.passwords.updated") if user_params.key?("password")
        redirect_to account_path
      else
        user_name = @user.name&.possessive || @user.email.possessive
        case user_params[:active]
        when "false"
          @user.update!(confirmed_at: nil, sign_in_count: 0)
          flash[:notice] = I18n.t("devise.activation.deactivated", user_name:)
        when "true"
          @user.send_confirmation_instructions
          flash[:notice] = I18n.t("devise.activation.reactivated", user_name:)
        end
        redirect_to user_path(@user)
      end
    elsif user_params.key?("password")
      format_error_messages
      @minimum_password_length = User.password_length.min
      render "devise/passwords/edit", locals: { resource: @user, resource_name: "user" }, status: :unprocessable_entity
    else
      format_error_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @organisation_id = params["organisation_id"]
    @resource = User.new
  end

  def create
    @resource = User.new(user_params.merge(org_params).merge(password_params))

    if valid_attributes? && @resource.save
      redirect_to created_user_redirect_path
    else
      unless @resource.errors[:organisation].empty?
        @resource.errors.add(:organisation_id, message: @resource.errors[:organisation])
        @resource.errors.delete(:organisation)
      end
      render :new, status: :unprocessable_entity
    end
  end

  def edit_password
    @minimum_password_length = User.password_length.min
    render "devise/passwords/edit", locals: { resource: @user, resource_name: "user" }
  end

  def deactivate
    if current_user.can_toggle_active?(@user)
      render "toggle_active", locals: { action: "deactivate" }
    else
      redirect_to user_path(@user)
    end
  end

  def reactivate
    if current_user.can_toggle_active?(@user)
      render "toggle_active", locals: { action: "reactivate" }
    else
      redirect_to user_path(@user)
    end
  end

private

  def valid_attributes?
    @resource.valid?
    if user_params[:role].present? && !current_user.assignable_roles.key?(user_params[:role].to_sym)
      @resource.errors.add :role, I18n.t("validations.role.invalid")
    end
    if user_params[:role].empty?
      @resource.errors.add :role, I18n.t("activerecord.errors.models.user.attributes.role.blank")
    end
    @resource.errors.empty?
  end

  def format_error_messages
    errors = @user.errors.to_hash
    @user.errors.clear
    errors.each do |attribute, message|
      @user.errors.add attribute.to_sym, format_error_message(attribute, message)
    end
  end

  def format_error_message(attribute, message)
    [attribute.to_s.humanize.capitalize, message].join(" ")
  end

  def search_term
    params["search"]
  end

  def password_params
    { password: SecureRandom.hex(8) }
  end

  def org_params
    return {} if current_user.support?

    { organisation: current_user.organisation }
  end

  def user_params
    if @user == current_user
      if current_user.data_coordinator? || current_user.support?
        params.require(:user).permit(:email, :name, :password, :password_confirmation, :role, :is_dpo, :is_key_contact)
      else
        params.require(:user).permit(:email, :name, :password, :password_confirmation)
      end
    elsif current_user.data_coordinator?
      params.require(:user).permit(:email, :name, :role, :is_dpo, :is_key_contact, :active)
    elsif current_user.support?
      params.require(:user).permit(:email, :name, :role, :is_dpo, :is_key_contact, :organisation_id, :active)
    end
  end

  def created_user_redirect_path
    if current_user.support?
      users_path
    else
      users_organisation_path(current_user.organisation)
    end
  end

  def find_resource
    @user = params[:id] ? User.find_by(id: params[:id]) : current_user
  end

  def authenticate_scope!
    if action_name == "create"
      head :unauthorized and return unless current_user.data_coordinator? || current_user.support?
    else
      render_not_found and return unless (current_user.organisation == @user.organisation) || current_user.support?
      render_not_found and return if action_name == "edit_password" && current_user != @user
      render_not_found and return unless action_name == "show" ||
        current_user.data_coordinator? || current_user.support? || current_user == @user
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  def aliased_user_edit(user, current_user)
    current_user == user ? edit_account_path : edit_user_path(user)
  end

  def perspective(user, current_user)
    current_user == user ? "Are you" : "Is this person"
  end

  def can_edit_names?(user, current_user)
    (current_user == user || current_user.data_coordinator? || current_user.support?) && user.active?
  end

  def can_edit_emails?(user, current_user)
    (current_user == user || current_user.data_coordinator? || current_user.support?) && user.active?
  end

  def can_edit_password?(user, current_user)
    current_user == user
  end

  def can_edit_roles?(user, current_user)
    (current_user.data_coordinator? || current_user.support?) && user.active?
  end

  def can_edit_dpo?(user, current_user)
    (current_user.data_coordinator? || current_user.support?) && user.active?
  end

  def can_edit_key_contact?(user, current_user)
    (current_user.data_coordinator? || current_user.support?) && user.active?
  end

  def can_edit_org?(current_user)
    current_user.data_coordinator? || current_user.support?
  end
end

app/views/users/_user_list.html.erb
<section class="app-table-group" tabindex="0" aria-labelledby="<%= title.dasherize %>">
  <%= govuk_table do |table| %>
    <%= table.caption(classes: %w[govuk-!-font-size-19 govuk-!-font-weight-regular]) do |caption| %>
     <%= render(SearchResultCaptionComponent.new(searched:, count: pagy.count, item_label:, total_count:, item: "users", path: request.path)) %>
       <% if current_user.support? %>
        <% query = searched.present? ? "?search=#{searched}" : nil %>
        <%= govuk_link_to "Download (CSV)", "#{request.path}.csv#{query}", type: "text/csv" %>
      <% end %>
    <% end %>
    <%= table.head do |head| %>
      <%= head.row do |row| %>
        <% row.cell(header: true, text: "Name and email adress", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Organisation and role", html_attributes: {
          scope: "col",
        }) %>
        <% row.cell(header: true, text: "Last logged in", html_attributes: {
          scope: "col",
        }) %>
      <% end %>
    <% end %>
    <% users.each do |user| %>
      <%= table.body do |body| %>
        <%= body.row do |row| %>
          <% row.cell(header: true, html_attributes: {
            scope: "row",
          }) do %>
            <%= simple_format(user_cell(user), {}, wrapper_tag: "span") %>
            <% if user.is_data_protection_officer? || user.is_key_contact? %>
              <br>
            <% end %>
            <% if user.is_data_protection_officer? %>
              <%= govuk_tag(
                    classes: "app-tag--small",
                    colour: "turquoise",
                    text: "Data protection officer",
                  ) %>
            <% else %>
              <%= "" %>
            <% end %>
            <% if user.is_key_contact? %>
              <%= govuk_tag(
                    classes: "app-tag--small",
                    colour: "turquoise",
                    text: "Key contact",
                  ) %>
            <% else %>
              <%= "" %>
            <% end %>
          <% end %>
          <% row.cell(text: simple_format(org_cell(user), {}, wrapper_tag: "div")) %>
          <% row.cell(text: user.active? ? user.last_sign_in_at&.to_formatted_s(:govuk_date) : "Deactivated") %>
          <%= govuk_link_to users_path(user) do %>
            <span class="govuk-visually-hidden">User </span><%= user.id %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</section>

app/views/users/edit.html.erb
<% content_for :title, current_user == @user ? "Change your personal details" : "Change #{@user.name.presence || 'this user'}’s personal details" %>

<% content_for :before_content do %>
  <%= govuk_back_link(href: :back) %>
<% end %>

<%= form_for(@user, as: :user, html: { method: :patch }) do |f| %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_error_summary %>

      <h1 class="govuk-heading-l">
        <%= content_for(:title) %>
      </h1>

      <%= f.govuk_text_field :name,
        label: { text: "Name", size: "m" },
        autocomplete: "name" %>

      <%= f.govuk_email_field :email,
        label: { text: "Email address", size: "m" },
        autocomplete: "email",
        spellcheck: "false" %>

      <% if current_user.data_coordinator? || current_user.support? %>
        <% roles = current_user.assignable_roles.map { |key, _| OpenStruct.new(id: key, name: key.to_s.humanize) } %>

        <%= f.govuk_collection_radio_buttons :role,
          roles,
          :id,
          :name,
          legend: { text: "Role", size: "m" } %>

        <%= f.govuk_collection_radio_buttons :is_dpo,
          [OpenStruct.new(id: true, name: "Yes"), OpenStruct.new(id: false, name: "No")],
          :id,
          :name,
          legend: { text: "#{perspective(@user, current_user)} the organisation’s data protection officer?", size: "m" } %>

        <%= f.govuk_collection_radio_buttons :is_key_contact,
          [OpenStruct.new(id: true, name: "Yes"), OpenStruct.new(id: false, name: "No")],
          :id,
          :name,
          legend: { text: "#{perspective(@user, current_user)} a key contact for this service?", size: "m" },
          hint: { text: "This is a person responsible for sharing information about social housing lettings and sales data within the organisation." } %>
      <% end %>

      <%= f.govuk_submit "Save changes" %>
    </div>
  </div>
<% end %>

app/views/users/edit_password.html.erb
<% content_for :title, "Change your password" %>

<% content_for :before_content do %>
  <%= govuk_back_link(
    text: 'Back',
    href: :back,
  ) %>
<% end %>

<%= form_for(@user, as: :user, html: { method: :patch }) do |f| %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_error_summary %>

      <h1 class="govuk-heading-l">
        <%= content_for(:title) %>
      </h1>

      <%= f.govuk_password_field :password,
        label: { text: "New password" },
        hint: @minimum_password_length ? { text: "Your password must be at least #{@minimum_password_length} characters and hard to guess." } : nil,
        autocomplete: "new-password"
      %>

      <%= f.govuk_password_field :password_confirmation,
        label: { text: "Confirm new password" }
      %>

      <%= f.govuk_submit "Update" %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<% item_label = format_label(@pagy.count, "user") %>
<% title = format_title(@searched, "Users", current_user, item_label, @pagy.count, nil) %>

<% content_for :title, title %>

<%= render partial: "organisations/headings", locals: current_user.support? ? { main: "Users", sub: nil } : { main: "Users", sub: current_user.organisation.name } %>

<% if current_user.data_coordinator? || current_user.support? %>
  <%= govuk_button_link_to "Invite user", new_user_path, html: { method: :get } %>
<% end %>

<%= render SearchComponent.new(current_user:, search_label: "Search by name or email address", value: @searched) %>

<%= govuk_section_break(visible: true, size: "m") %>

<%= render partial: "users/user_list", locals: { users: @users, title:, pagy: @pagy, searched: @searched, item_label:, total_count: @total_count } %>
<%== render partial: "pagy/nav", locals: { pagy: @pagy, item_name: "users" } %>

app/views/users/new.html.erb
<% content_for :title, "Invite somebody to submit CORE data" %>

<% content_for :before_content do %>
  <%= govuk_back_link(href: :back) %>
<% end %>

<%= form_for(@resource, as: :user, html: { method: :post }) do |f| %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_error_summary %>

      <h1 class="govuk-heading-l">
        <%= content_for(:title) %>
      </h1>

      <%= f.govuk_text_field :name,
        autocomplete: "name",
        label: { text: "Name", size: "m" } %>

      <%= f.govuk_email_field :email,
        label: { text: "Email address", size: "m" },
        autocomplete: "email",
        spellcheck: "false",
        value: @resource.email %>

      <% if current_user.support? %>
        <% null_option = [OpenStruct.new(id: "", name: "Select an option")] %>
        <% organisations = Organisation.all.map { |org| OpenStruct.new(id: org.id, name: org.name) } %>
        <% answer_options = null_option + organisations %>

        <% if @organisation_id %>
          <% organisation = Organisation.find(@organisation_id) %>
          <% answer_options = [OpenStruct.new(id: organisation.id, name: organisation.name)] %>
        <% end %>

          <%= f.govuk_collection_select :organisation_id,
            answer_options,
            :id,
            :name,
            label: { text: "Organisation", size: "m" },
            options: { disabled: [""], selected: @organisation_id ? answer_options.first : "" } %>
      <% end %>


      <% hints_for_roles = { data_provider: ["Default role for this organisation", "Can view and submit logs for this organisation"],  data_coordinator: ["Can view and submit logs for this organisation and any of its managing agents", "Can manage details for this organisation", "Can manage users for this organisation"],   support: nil } %>

      <% roles_with_hints = current_user.assignable_roles.map { |key, _| OpenStruct.new(id: key, name: key.to_s.humanize, description: hints_for_roles[key.to_sym]) } %>

      <%= f.govuk_collection_radio_buttons :role,
                                           roles_with_hints,
                                           :id,
                                           :name,
                                           ->(option) do
                                             result = option.description&.sum(nil) {|hint| content_tag(:li, hint) }
                                           end,
                                           legend: { text: "Role", size: "m" } %>

      <%= f.govuk_submit "Continue" %>
    </div>
  </div>
<% end %>

app/views/users/reset_password.html.erb
<% content_for :title, "Reset your password" %>

<% content_for :before_content do %>
  <%= govuk_back_link(
    text: 'Back',
    href: :back,
  ) %>
<% end %>

<%= form_for(@user, as: :user, url: password_path(User), html: { method: :put }) do |f| %>
  <%= f.hidden_field :reset_password_token %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_error_summary %>

      <h1 class="govuk-heading-l">
        <%= content_for(:title) %>
      </h1>

      <%= f.govuk_password_field :password,
        label: { text: "New password" },
        hint: @minimum_password_length ? { text: "Your password must be at least #{@minimum_password_length} characters and hard to guess." } : nil,
        autocomplete: "new-password"
      %>

      <%= f.govuk_password_field :password_confirmation,
        label: { text: "Confirm new password" }
      %>

      <%= f.govuk_submit "Update" %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<% content_for :title, current_user == @user ? "Your account" : "#{@user.name.presence || @user.email}’s account" %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l">
      <%= content_for(:title) %>
    </h1>
    <p>
      <% if current_user.can_toggle_active?(@user) %>
        <% if @user.active? %>
          <%= govuk_link_to "Deactivate user", "/users/#{@user.id}/deactivate" %>
        <% else %>
          <span class="app-!-colour-muted govuk-!-margin-right-2">
            This user has been deactivated. <%= govuk_link_to "Reactivate user", "/users/#{@user.id}/reactivate" %>
          </span>
        <% end %>
      <% end %>
    </p>

    <h2 class="govuk-heading-m">
      Personal details
    </h2>
    <%= govuk_summary_list do |summary_list| %>
      <%= summary_list.row do |row|
            row.key { "Name" }
            row.value { @user.name }
            if can_edit_names?(@user, current_user)
              row.action(visually_hidden_text: "name", href: aliased_user_edit(@user, current_user), html_attributes: { "data-qa": "change-name" })
            else
              row.action
            end
          end %>

      <%= summary_list.row do |row|
            row.key { "Email address" }
            row.value { @user.email }
            if can_edit_emails?(@user, current_user)
              row.action(visually_hidden_text: "email address", href: aliased_user_edit(@user, current_user), html_attributes: { "data-qa": "change-email-address" })
            else
              row.action
            end
          end %>

      <%= summary_list.row do |row|
            row.key { "Password" }
            row.value { "••••••••" }
            if can_edit_password?(@user, current_user)
              row.action(
                visually_hidden_text: "password",
                href: edit_password_account_path,
                html_attributes: { "data-qa": "change-password" },
              )
            else
              row.action
            end
          end %>

      <%= summary_list.row do |row|
            row.key { "Organisation" }
            row.value { @user.organisation.name }
            row.action
          end %>

      <%= summary_list.row do |row|
            row.key { "Role" }
            row.value { @user.role&.humanize }
            if can_edit_roles?(@user, current_user)
              row.action(
                visually_hidden_text: "role",
                href: aliased_user_edit(@user, current_user),
                html_attributes: { "data-qa": "change-role" },
              )
            else
              row.action
            end
          end %>

      <%= summary_list.row do |row|
            row.key { "Data protection officer" }
            row.value { @user.is_data_protection_officer? ? "Yes" : "No" }
            if can_edit_dpo?(@user, current_user)
              row.action(
                visually_hidden_text: "if data protection officer",
                href: aliased_user_edit(@user, current_user),
                html_attributes: { "data-qa": "change-data-protection-officer" },
              )
            else
              row.action
            end
          end %>

      <%= summary_list.row do |row|
            row.key { "Key contact" }
            row.value { @user.is_key_contact? ? "Yes" : "No" }
            if can_edit_key_contact?(@user, current_user)
              row.action(
                visually_hidden_text: "if a key contact",
                href: aliased_user_edit(@user, current_user),
                html_attributes: { "data-qa": "change-key-contact" },
              )
            else
              row.action
            end
          end %>
    <% end %>
  </div>
</div>

app/views/users/toggle-active.html.erb
<% content_for :title, "#{action.capitalize} #{@user.name.presence || @user.email}’s account" %>

<div class="govuk-grid-row">
    <%= form_for(@user, as: :user, html: { method: :patch }) do |f| %>
        <div class="govuk-grid-column-two-thirds-from-desktop"> 
            <h1 class="govuk-heading-l">
                <span class="govuk-caption-l"><%= @user.name %></span>
                Are you sure you want to <%= action %> this user?
            </h1>
            <% if action == "deactivate" %>
                <p>Deactivating this user will mean they can no longer access this service to submit CORE data.</p>
                <p>Any logs this user has already submitted will not be affected.</p>
            <% end %>
            <% active_value = action == "deactivate" ? false : true %>
            <div hidden> 
                <%= f.govuk_text_field :active,
                value: active_value %>
            </div>
            <%= f.govuk_submit "I’m sure - #{action} this user", warning: action == "deactivate" %>
            <p class="govuk-body">
                <%= govuk_link_to("No - I’ve changed my mind", user_path(@user)) %>
            </p>
        </div>
    </div>
    <% end %>
</div>

app/views/users/toggle_active.html.erb
<% content_for :title, "#{action.capitalize} #{@user.name.presence || @user.email}’s account" %>

<div class="govuk-grid-row">
    <%= form_for(@user, as: :user, html: { method: :patch }) do |f| %>
        <div class="govuk-grid-column-two-thirds-from-desktop">
            <h1 class="govuk-heading-l">
                <span class="govuk-caption-l"><%= @user.name %></span>
                Are you sure you want to <%= action %> this user?
            </h1>
            <% if action == "deactivate" %>
                <p>Deactivating this user will mean they can no longer access this service to submit CORE data.</p>
                <p>Any logs this user has already submitted will not be affected.</p>
            <% end %>
            <% active_value = action != "deactivate" %>

            <%= f.hidden_field :active, value: active_value %>

            <%= f.govuk_submit "I’m sure – #{action} this user", warning: action == "deactivate" %>

            <p class="govuk-body">
                <%= govuk_link_to("No – I’ve changed my mind", user_path(@user)) %>
            </p>
        </div>
    </div>
    <% end %>
</div>